brew "htop"
brew "wget"

brew "xcodes"

brew "pyenv"
brew "zsh-autosuggestions"

cask "font-jetbrains-mono-nerd-font"

cask "intellij-idea"
cask "webstorm"
cask "datagrip"

cask "telegram-desktop"
cask "google-chrome"
cask "discord"
cask "slack"

cask "prismlauncher"
